import { PlanetEntry } from "./types";

const NASA_SOURCE = { sourceName: "NASA Planetary Fact Sheets", sourceUrl: "https://nssdc.gsfc.nasa.gov/planetary/factsheet/" };

// orbitRadiusPx / orbitPeriodSec / relativeSize are for the interactive
// orbit view only — compressed to fit a screen and to keep outer planets
// from taking a minute to complete a visible loop. They are NOT to scale;
// the planet detail pages carry the real, sourced numbers.
export const planets: PlanetEntry[] = [
  {
    id: "mercury", slug: "mercury", name: "Mercury", category: "planet",
    tagline: "The swift, scorched innermost world",
    summary: "Mercury is the smallest planet and the closest to the Sun, with almost no atmosphere to soften its extremes.",
    deepDive: "With no meaningful atmosphere to trap heat, Mercury's surface swings from about 427°C in direct sunlight to -173°C in shadow. It rotates so slowly (58.6 Earth days) relative to its short year (88 days) that a single Mercury solar day lasts about 176 Earth days.",
    stats: [
      { label: "Diameter", value: "4,879", unit: "km", approximate: true },
      { label: "Distance from Sun", value: "57.9M", unit: "km (0.39 AU)", approximate: true },
      { label: "Day length", value: "58.6", unit: "Earth days" },
      { label: "Year length", value: "88", unit: "Earth days" },
      { label: "Moons", value: "0", unit: "" },
      { label: "Surface temp", value: "-173 to 427", unit: "°C", approximate: true }
    ],
    facts: ["A year on Mercury is shorter than its own day.", "Mercury has the most eccentric (least circular) orbit of any planet."],
    colorHex: "#B8AFA6",
    orbitRadiusPx: 90, orbitPeriodSec: 8, relativeSize: 5,
    ...NASA_SOURCE
  },
  {
    id: "venus", slug: "venus", name: "Venus", category: "planet",
    tagline: "Earth's twin in size, hell in climate",
    summary: "Venus is blanketed in thick carbon-dioxide clouds that trap heat so effectively it's the hottest planet in the solar system.",
    deepDive: "A runaway greenhouse effect from a CO2-rich atmosphere pushes Venus's surface temperature above 460°C — hotter than Mercury despite being farther from the Sun. Venus also rotates backward relative to most planets, so its sun rises in the west.",
    stats: [
      { label: "Diameter", value: "12,104", unit: "km", approximate: true },
      { label: "Distance from Sun", value: "108.2M", unit: "km (0.72 AU)", approximate: true },
      { label: "Day length", value: "243", unit: "Earth days (retrograde)" },
      { label: "Year length", value: "224.7", unit: "Earth days" },
      { label: "Moons", value: "0", unit: "" },
      { label: "Surface temp", value: "≈ 464", unit: "°C", approximate: true }
    ],
    facts: ["A day on Venus is longer than its year.", "Venus's surface pressure is about 90 times Earth's."],
    colorHex: "#E8C170",
    orbitRadiusPx: 130, orbitPeriodSec: 13, relativeSize: 7,
    ...NASA_SOURCE
  },
  {
    id: "earth", slug: "earth", name: "Earth", category: "planet",
    tagline: "The only known home for life",
    summary: "Earth is the third planet from the Sun and the only world we know of with liquid water on the surface and life.",
    deepDive: "A nitrogen-oxygen atmosphere shields the surface from harmful radiation, and a magnetic field generated by the molten outer core deflects the solar wind. Roughly 71% of the surface is covered by ocean.",
    stats: [
      { label: "Diameter", value: "12,742", unit: "km", approximate: true },
      { label: "Distance from Sun", value: "149.6M", unit: "km (1.0 AU)", approximate: true },
      { label: "Day length", value: "23.9", unit: "hours" },
      { label: "Year length", value: "365.25", unit: "days" },
      { label: "Moons", value: "1", unit: "(the Moon)" },
      { label: "Avg. surface temp", value: "≈ 15", unit: "°C", approximate: true }
    ],
    facts: ["Earth isn't a perfect sphere — it bulges slightly at the equator from its own rotation."],
    colorHex: "#4E8FE0",
    orbitRadiusPx: 170, orbitPeriodSec: 18, relativeSize: 7,
    ...NASA_SOURCE
  },
  {
    id: "mars", slug: "mars", name: "Mars", category: "planet",
    tagline: "The Red Planet, most explored world beyond Earth",
    summary: "Mars gets its rust-red color from iron oxide covering its surface, and hosts the largest known volcano in the solar system.",
    deepDive: "Olympus Mons rises about three times the height of Mount Everest, and Valles Marineris is a canyon system long enough to stretch across the continental United States. Strong geological evidence points to liquid water having flowed on Mars in its distant past.",
    stats: [
      { label: "Diameter", value: "6,779", unit: "km", approximate: true },
      { label: "Distance from Sun", value: "227.9M", unit: "km (1.52 AU)", approximate: true },
      { label: "Day length", value: "24.6", unit: "hours" },
      { label: "Year length", value: "687", unit: "Earth days" },
      { label: "Moons", value: "2", unit: "(Phobos & Deimos)" },
      { label: "Avg. surface temp", value: "≈ -63", unit: "°C", approximate: true }
    ],
    facts: ["Olympus Mons is roughly three times the height of Mount Everest."],
    colorHex: "#C1573A",
    orbitRadiusPx: 210, orbitPeriodSec: 24, relativeSize: 6,
    ...NASA_SOURCE
  },
  {
    id: "jupiter", slug: "jupiter", name: "Jupiter", category: "planet",
    tagline: "The solar system's giant",
    summary: "Jupiter is by far the largest planet — a gas giant with a storm, the Great Red Spot, that's raged for centuries at least.",
    deepDive: "Jupiter is made mostly of hydrogen and helium and has no true solid surface. Its Great Red Spot is a storm larger than Earth itself. Jupiter's powerful magnetic field and dozens of moons — including the four large Galilean moons discovered in 1610 — make it effectively a miniature planetary system of its own.",
    stats: [
      { label: "Diameter", value: "139,820", unit: "km", approximate: true },
      { label: "Distance from Sun", value: "778.5M", unit: "km (5.2 AU)", approximate: true },
      { label: "Day length", value: "≈ 9.9", unit: "hours", approximate: true },
      { label: "Year length", value: "≈ 11.9", unit: "Earth years", approximate: true },
      { label: "Known moons", value: "90+", unit: "", approximate: true }
    ],
    facts: ["The Great Red Spot is a storm bigger than the entire Earth."],
    colorHex: "#D9A066",
    orbitRadiusPx: 270, orbitPeriodSec: 34, relativeSize: 14,
    ...NASA_SOURCE
  },
  {
    id: "saturn", slug: "saturn", name: "Saturn", category: "planet",
    tagline: "The ringed jewel of the solar system",
    summary: "Saturn's spectacular ring system, made mostly of ice and rock particles, makes it one of the most recognizable objects in the sky.",
    deepDive: "Saturn is less dense than water — in principle, it would float in an ocean big enough to hold it. Its largest moon, Titan, has a thick atmosphere and lakes of liquid methane, making it one of the most Earth-like worlds in terms of surface processes, despite the extreme cold.",
    stats: [
      { label: "Diameter", value: "116,460", unit: "km", approximate: true },
      { label: "Distance from Sun", value: "1.43B", unit: "km (9.5 AU)", approximate: true },
      { label: "Year length", value: "≈ 29.4", unit: "Earth years", approximate: true },
      { label: "Known moons", value: "140+", unit: "", approximate: true }
    ],
    facts: ["Saturn's rings are, proportionally, remarkably thin — often just tens of meters thick."],
    colorHex: "#E8D2A0",
    orbitRadiusPx: 320, orbitPeriodSec: 44, relativeSize: 13,
    ...NASA_SOURCE
  },
  {
    id: "uranus", slug: "uranus", name: "Uranus", category: "planet",
    tagline: "The ice giant tipped on its side",
    summary: "Uranus rotates on an axis tilted roughly 98 degrees, so it essentially rolls around the Sun rather than spinning upright.",
    deepDive: "Uranus and Neptune are classed as 'ice giants,' distinct from the gas giants Jupiter and Saturn, because a larger share of their interior is made of water, ammonia, and methane ices. Uranus's blue-green color comes from methane absorbing red light in its atmosphere.",
    stats: [
      { label: "Diameter", value: "50,724", unit: "km", approximate: true },
      { label: "Distance from Sun", value: "2.87B", unit: "km (19.8 AU)", approximate: true },
      { label: "Year length", value: "≈ 84", unit: "Earth years", approximate: true },
      { label: "Axial tilt", value: "≈ 98", unit: "degrees", approximate: true },
      { label: "Known moons", value: "27", unit: "", approximate: true }
    ],
    facts: ["Uranus's moons are named after Shakespeare and Alexander Pope characters, not mythological figures."],
    colorHex: "#8FD9D9",
    orbitRadiusPx: 365, orbitPeriodSec: 54, relativeSize: 10,
    ...NASA_SOURCE
  },
  {
    id: "neptune", slug: "neptune", name: "Neptune", category: "planet",
    tagline: "The windiest world, found by math before a telescope",
    summary: "Neptune is the most distant known planet and hosts the fastest winds recorded in the solar system.",
    deepDive: "Neptune's existence was predicted mathematically from irregularities in Uranus's orbit before it was ever observed directly — the only planet discovered this way. Its largest moon, Triton, orbits backward relative to Neptune's rotation, suggesting it's a captured Kuiper Belt object.",
    stats: [
      { label: "Diameter", value: "49,244", unit: "km", approximate: true },
      { label: "Distance from Sun", value: "4.5B", unit: "km (30.1 AU)", approximate: true },
      { label: "Year length", value: "≈ 165", unit: "Earth years", approximate: true },
      { label: "Known moons", value: "14", unit: "", approximate: true }
    ],
    facts: ["Neptune is the only planet in the solar system not visible to the naked eye from Earth."],
    colorHex: "#5A7FE0",
    orbitRadiusPx: 405, orbitPeriodSec: 64, relativeSize: 10,
    ...NASA_SOURCE
  }
];

export function getPlanetBySlug(slug: string) {
  return planets.find((p) => p.slug === slug);
}
